name: Build and Deploy to GitHub Pages

on:
  # 1. Automatic Trigger: Runs every 2 days at 3 AM UTC.
  # You can adjust the cron schedule. '0 3 */2 * *' means:
  # 0: minute, 3: hour, */2: every 2nd day of the month, *: any month, *: any day of the week.
  schedule:
    - cron: '0 3 */2 * *'

  # 2. Manual Trigger: Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

  # 3. On Push: Runs when you push changes to the main branch (e.g., template updates).
  push:
    branches:
      - main # Or master, depending on your default branch name

# Permissions needed for the deployment actions to work correctly.
permissions:
  contents: write 
  pages: write 
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build static site
        run: npm run build

      - name: Commit and push generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: Auto-update workflows and site'
          file_pattern: 'docs/* index.json'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # The path to the folder that contains the built site
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4